# Generated by Django 5.1.4 on 2024-12-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20230801_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='subject',
        ),
    ]
