# Generated by Django 5.1.4 on 2024-12-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_rename_content_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
